
import os 
os.system ("clear")
import time 
import random 
print ("\033[92m | |_ _ __ _   _  ___  ___ __ _| | |  ")
print ("\033[92m | __| '__| | | |/ _ \/ __/ _` | | |  ")
print ("\033[93m | |_| |  | |_| |  __/ (_| (_| | | |  ")
print ("\033[93m  \__|_|   \__,_|\___|\___\__,_|_|_| ")
print ()
print ()
name = ("\033[96m Please follow my page on Instagram ahu_orphan")
for char in name:
 print (char,end="",flush=True)
 time.sleep(0.1)
print ()
print ()
nam = input ("\033[92m Enter the tool's password: ")
if nam == "orphan" :
 print ()
 print ("\033[92m Correct password. Welcome...")
 print ()
 print ()
 input ("\033[96m Enter the number with the country code:")
 time.sleep(0.5)
 print ()
 print ()
 print ()
 print ("\033[93m Searching for information...")
 time.sleep(16)
 print ()
 k = ("\033[92m config                :     ")
 for char in k:
  print (char,end="",flush=True)
  time.sleep(0.2)
 print ()
 q = ("\033[92m transitional          :     ")
 for char in q:
  print (char,end="",flush=True)
  time.sleep(0.2)
 print ()
 print ()
 print ("\033[92m silentJSONParsing   :  true ")
 time.sleep(2)
 print ()
 print ("\033[92m forcedJSONParsing   :  true ")
 time.sleep(2)
 print ()
 print ("\033[93m clarifyTimeoutError :  true ")
 time.sleep(2)
 print ()
 print ("\033[93m adapter             :  xhr, http ")
 time.sleep(2)
 print ()
 print ("\033[92m transformRequest    :  null ")
 time.sleep(2)
 print ()
 print ("\033[92m transformResponse   :  null ")
 time.sleep(2)
 print ()
 print ("\033[93m timeout             :  0 ")
 time.sleep(2)
 print ()
 print ("\033[93m xsrfCookieName      :  XSRFG-TOKEN ")
 time.sleep(2)
 print ()
 print ("\033[92m xsrfHeaderName      :  X-XSRFG-TOKEN ")
 time.sleep(2)
 print ()
 print ("\033[92m maxContentLength    :  +1 ")
 time.sleep(2)
 print ()
 print ("\033[92m maxBodyLength       :  0 ")
 time.sleep(2)
 print ()
 print ("\033[91m env                 :  {} ")
 time.sleep(2)
 print ()
 print ("\033[93m Accept              :  application/json, text/plain, */* ")
 time.sleep(2)
 print ()
 print ("\033[93m Content-Type        :  application/json, charset=UTF-5 ")
 time.sleep(2)
 print ()
 print ("\033[92m accept-encoding     :  gzip ")
 time.sleep(2)
 print ()
 print ("\033[92m user-agent          :  Truecaller/11.95.5 (Android;14) ")
 time.sleep(2)
 print ()
 print ("\033[93m countryCode         :  null ")
 time.sleep(2)
 print ()
 print ("\033[93m type                :  4 ")
 time.sleep(2)
 print ()
 print ("\033[92m encodeing           :  json ")
 time.sleep(2)
 print ()
 print ("\033[93m method              :  get ")
 time.sleep(2)
 print ()
 print ("\033[93m status              :  400 ")
 print ()
else:
 print ()
 print ()
 print ("\033[91m The password you entered is incorrect ")
 print ()
 print ()
 print ("\033[91m Error ")
 time.sleep(2)

